// <auto-generated />
using System;
using InterShip.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InterShip.Infrastructure.Migrations
{
    [DbContext(typeof(InterShipDbContext))]
    partial class InterShipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InterShip.Core.Models.AuthUser", b =>
                {
                    b.Property<int>("AuthUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthUserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AuthUsers");

                    b.HasData(
                        new
                        {
                            AuthUserID = 1,
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(7809),
                            Email = "admin@intership.com",
                            IsActive = true,
                            PasswordHash = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InterShip.Core.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeLocationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DepartmentID");

                    b.HasIndex("OfficeLocationID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("InterShip.Core.Models.LocationScan", b =>
                {
                    b.Property<int>("LocationScanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScannedByUserID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationScanID");

                    b.HasIndex("OfficeLocationID");

                    b.HasIndex("ScannedByUserID");

                    b.HasIndex("ShipmentID");

                    b.ToTable("LocationScans");
                });

            modelBuilder.Entity("InterShip.Core.Models.MailboxItem", b =>
                {
                    b.Property<int>("MailboxItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpectedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PickedUpDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShipmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MailboxItemID");

                    b.HasIndex("OfficeLocationID");

                    b.HasIndex("ShipmentID");

                    b.HasIndex("UserID");

                    b.ToTable("MailboxItems");
                });

            modelBuilder.Entity("InterShip.Core.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InterShip.Core.Models.OfficeLocation", b =>
                {
                    b.Property<int>("OfficeLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("QRCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("OfficeLocationID");

                    b.ToTable("OfficeLocations");

                    b.HasData(
                        new
                        {
                            OfficeLocationID = 1,
                            Address = "123 Main St, City, State 12345",
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(7990),
                            IsActive = true,
                            Name = "Main Office"
                        },
                        new
                        {
                            OfficeLocationID = 2,
                            Address = "456 Oak Ave, City, State 12345",
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(8001),
                            IsActive = true,
                            Name = "Branch Office A"
                        },
                        new
                        {
                            OfficeLocationID = 3,
                            Address = "789 Pine St, City, State 12345",
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(8003),
                            IsActive = true,
                            Name = "Branch Office B"
                        });
                });

            modelBuilder.Entity("InterShip.Core.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ToLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ShipmentID");

                    b.HasIndex("FromLocationID");

                    b.HasIndex("SenderID");

                    b.HasIndex("ToLocationID");

                    b.HasIndex("TrackingNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("InterShip.Core.Models.ShipmentEvent", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoURL")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ShipmentID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("EventID");

                    b.HasIndex("PerformedBy");

                    b.HasIndex("ShipmentID");

                    b.ToTable("ShipmentEvents");
                });

            modelBuilder.Entity("InterShip.Core.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OfficeLocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OfficeLocationID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(8032),
                            Email = "admin@company.com",
                            IsActive = true,
                            Name = "Admin User",
                            OfficeLocationID = 1,
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(8038),
                            Email = "john.driver@company.com",
                            IsActive = true,
                            Name = "John Driver",
                            OfficeLocationID = 1,
                            Role = "Driver"
                        },
                        new
                        {
                            UserID = 3,
                            CreatedDate = new DateTime(2025, 10, 11, 23, 31, 31, 173, DateTimeKind.Utc).AddTicks(8041),
                            Email = "jane.sender@company.com",
                            IsActive = true,
                            Name = "Jane Sender",
                            OfficeLocationID = 2,
                            Role = "Sender"
                        });
                });

            modelBuilder.Entity("InterShip.Core.Models.Department", b =>
                {
                    b.HasOne("InterShip.Core.Models.OfficeLocation", "OfficeLocation")
                        .WithMany()
                        .HasForeignKey("OfficeLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("InterShip.Core.Models.LocationScan", b =>
                {
                    b.HasOne("InterShip.Core.Models.OfficeLocation", "OfficeLocation")
                        .WithMany()
                        .HasForeignKey("OfficeLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.User", "ScannedByUser")
                        .WithMany()
                        .HasForeignKey("ScannedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeLocation");

                    b.Navigation("ScannedByUser");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("InterShip.Core.Models.MailboxItem", b =>
                {
                    b.HasOne("InterShip.Core.Models.OfficeLocation", "OfficeLocation")
                        .WithMany("MailboxItems")
                        .HasForeignKey("OfficeLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InterShip.Core.Models.User", "User")
                        .WithMany("MailboxItems")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OfficeLocation");

                    b.Navigation("Shipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterShip.Core.Models.Notification", b =>
                {
                    b.HasOne("InterShip.Core.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterShip.Core.Models.Shipment", b =>
                {
                    b.HasOne("InterShip.Core.Models.OfficeLocation", "FromLocation")
                        .WithMany("FromShipments")
                        .HasForeignKey("FromLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.User", "Sender")
                        .WithMany("SentShipments")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.OfficeLocation", "ToLocation")
                        .WithMany("ToShipments")
                        .HasForeignKey("ToLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("Sender");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("InterShip.Core.Models.ShipmentEvent", b =>
                {
                    b.HasOne("InterShip.Core.Models.User", "PerformedByUser")
                        .WithMany("PerformedEvents")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InterShip.Core.Models.Shipment", "Shipment")
                        .WithMany("Events")
                        .HasForeignKey("ShipmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("InterShip.Core.Models.User", b =>
                {
                    b.HasOne("InterShip.Core.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("InterShip.Core.Models.OfficeLocation", "OfficeLocation")
                        .WithMany("Users")
                        .HasForeignKey("OfficeLocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("OfficeLocation");
                });

            modelBuilder.Entity("InterShip.Core.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InterShip.Core.Models.OfficeLocation", b =>
                {
                    b.Navigation("FromShipments");

                    b.Navigation("MailboxItems");

                    b.Navigation("ToShipments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("InterShip.Core.Models.Shipment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("InterShip.Core.Models.User", b =>
                {
                    b.Navigation("MailboxItems");

                    b.Navigation("Notifications");

                    b.Navigation("PerformedEvents");

                    b.Navigation("SentShipments");
                });
#pragma warning restore 612, 618
        }
    }
}
